name: Android Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      - name: Setup Godot
        run: |
          wget -q https://github.com/godotengine/godot/releases/download/4.6.2-stable/Godot_v4.6.2-stable_linux.x86_64.zip
          unzip -q Godot_v4.6.2-stable_linux.x86_64.zip
          chmod +x Godot_v4.6.2-stable_linux.x86_64
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Cache Android Export Templates
        uses: actions/cache@v3
        with:
          path: ~/.local/share/godot/export_templates
          key: ${{ runner.os }}-godot-export-templates-4.6.2
          restore-keys: |
            ${{ runner.os }}-godot-export-templates-
      - name: Install Android Export Templates
        run: |
          if [ ! -d ~/.local/share/godot/export_templates/4.6.2.stable ]; then
             ./Godot_v4.6.2-stable_linux.x86_64 --headless --install-android-build-template
          fi
      - name: Build
        run: dotnet build Polytoria.sln -c Release && ./Godot_v4.6.2-stable_linux.x86_64 --headless --export-release "Android" build/polytoria.apk
      - uses: actions/upload-artifact@v4
        with:
          name: polytoria-android
          path: build/polytoria.apk
